// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// -----------------------------------------------------------------------------
// ISTO NÃO É SEGREDO — NÃO GITIGNORE ESTE ARQUIVO
// -----------------------------------------------------------------------------
// `apiKey`, `appId`, `projectId` etc. abaixo identificam o app Web no
// Firebase; eles são servidos dentro do próprio bundle JS para qualquer
// visitante do site, por construção — não há como rodar um app Firebase Web
// sem expor esta config ao navegador. Isto é diferente de uma chave de API
// de servidor (ex.: uma service account): não dá acesso a nada sozinho.
//
// Quem protege os dados é a Security Rules (`firestore.rules`) e a lista de
// domínios autorizados no Firebase Auth — nunca a obscuridade desta config.
// Remover este arquivo do controle de versão (ou tentar escondê-lo) não
// aumenta a segurança em nada e QUEBRA O BUILD/CI, porque ele precisa
// existir em toda máquina que compila o app. Se você chegou aqui querendo
// "consertar um vazamento": não há vazamento para consertar.
//
// Referência: https://firebase.google.com/docs/projects/api-keys
// -----------------------------------------------------------------------------
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgVAyNTwdqn_VVbIYJJ4NjrTOb5JRcJZ4',
    appId: '1:746425158513:web:79f5bc6d90eaec72af44d0',
    messagingSenderId: '746425158513',
    projectId: 'evolab-cafelabs',
    authDomain: 'evolab-cafelabs.firebaseapp.com',
    storageBucket: 'evolab-cafelabs.firebasestorage.app',
  );
}
